apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keda-values
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kepungnzai/keda-aks-deploy
  ref:
    branch: main
