apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keda-values
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: keda-values
  path: ./keda
  prune: true
  targetNamespace: keda
